### ISSUE TITLE
macros are fragile: don't assume specific tree shapes and symbol organizations

### ISSUE THREAD

**Issue by paulp** [sirthias/parboiled2#120]
runSubParser will not work with almost any code except that which is written in exactly the fashion of the single test case. You have to be extremely careful with macro manipulations and you should definitely expect there are a bunch of cases you're not covering and try to issue some kind of meaningful error. In my cases my available errors were the one shown below and a straight up match error when the tree didn't match the expectation.

Presumably this is a consequence of something assuming the immediately enclosing entity is the Parser class, but as you see below, it isn't necessarily. It isn't even necessarily in the owner chain at all - the method might be being defined in some other class which has Parser as a self-type.
```
  abstract class ParserWithSubParser extends TestParser1[Int] {
    object Bob {
      def Rule = rule(oneOrMore(runSubParser(new SubParser(_).intNumber)).separatedBy(',') ~ EOI ~> (_.sum))
    }
    def InputLine = Bob.Rule
    // [error] /l/src/scala/parboiled2/parboiled-core/src/test/scala/org/parboiled2/RunSubParserSpec.scala:29: type mismatch;
    // [error]  found   : ParserWithSubParser.this.Bob.type
    // [error]  required: org.parboiled2.Parser
    // [error]       def Rule = rule(oneOrMore(runSubParser(new SubParser(_).intNumber)).separatedBy(',') ~ EOI ~> (_.sum))
    // [error]                      ^
    // [error] one error found
    // [error] (parboiledCore/test:compile) Compilation failed
    // [error] Total time: 14 s, completed Dec 9, 2014 3:50:42 PM
  }
```

Here is the relevant code:

```
      def rewrite(arg: TermName, tree: Tree): Tree =
        tree match {
          case Block(statements, res) ⇒ block(statements, rewrite(arg, res))
          case q"$p.$rule" ⇒ q"""
            val $arg = new __SubParserInput()  // TODO: avoid re-allocation by re-using a cached instance
            val __subParser = $p
            val offset = cursor
            __subParser.copyStateFrom(this, offset)
            try __subParser.$rule ne null
            finally this.copyStateFrom(__subParser, -offset)"""
          case x ⇒ c.abort(x.pos, "Illegal runSubParser expr: " + show(x))
        }

      val q"($arg ⇒ $body)" = c.untypecheck(fTree)
      rewrite(arg.name, body)
```

```val q"($arg ⇒ $body)" = c.untypecheck(fTree)``` is extremely optimistic regarding the possible shape of the tree. In general ```val <pattern> = <thing>``` is equivalent to a blind get on an Option, and equally well-advised.

**Comment by sirthias** [comment]
I don't care much about familiarity as this is a very subjective property.
In particular I don't think trying to mimic parser combinator naming, DSL, etc. would be a good idea for pb2.

However, I can subscribe to your wish of establishing a cleaner and especially better documented boundary between the input to the parser generator and the custom (runtime) user code.
Had we chosen to go for an external DSL for grammar definition this boundary would likely be easier to see. An internal Scala DSL comes with all kinds of benefits but also with the one important drawback of blurring this line.
