### ISSUE TITLE
A new stable release?

### ISSUE THREAD

**Issue by lihaoyi** [sirthias/parboiled2#131]
Any chance of publishing what we have right now both for Parboiled2 itself as well as the Scala parser? I'd like to use it and improve it, but it doesn't make sense to improve something (the parser) which will not be properly published/usable for the forseeable future.

**Comment by sirthias** [comment]
I don't currently plan to really publish the ScalaParser as a stand-alone entity to be used independently as I won't have any capacity to improve/maintain it.
I regard it more as a "complex example".

**Comment by lihaoyi** [comment]
How about publishing parboiled itself in its current state? I'd love to
maintain/publish the scala parser but cannot rely on snapshots

**Comment by sirthias** [comment]
Ok. I'll see what I can do. I might just publish 2.1.0 with more or less the current state in order to ship the fixes and improvements that are already in.

**Comment by sirthias** [comment]
Ok, just published 2.1.0 to sonatype, should hit maven central soon.

**Comment by lihaoyi** [comment]
Cool, thanks!

**Comment by lihaoyi** [comment]
@alexander-myltsev any chance of a Scala.js release? ^_^

**Comment by alexander-myltsev** [comment]
Sure, will make to as soon as I can.

**Comment by alexander-myltsev** [comment]
@lihaoyi , https://github.com/alexander-myltsev/parboiled2/commits/scala-2.11-scalajs-0.6.x . `sbt scalaParser/fastOptJS` does not pass. Please, take a look why.

**Comment by lihaoyi** [comment]
@alexander-myltsev is this the error message you got?

```scala
[error] (parboiledCore/*:update) sbt.ResolveException: unresolved dependency: name.myltsev#shapeless_sjs0.6_2.11;2.1.0: not found
```

Seems pretty self-explanatory to me, unless I'm missing something obvious

**Comment by alexander-myltsev** [comment]
Oops... Sure no. You should `sbt publishLocal` that https://github.com/alexander-myltsev/shapeless/commits/shapeless-2.1.0-scalajs-0.6.x beforehand.
