### ISSUE TITLE
How can I create a parser / grammar without available input?

### ISSUE THREAD

**Issue by EECOLOR** [sirthias/parboiled2#133]
I have another format that I need to translate into parser rules. As far as I can tell the parser rules can only be created within sub classes of a parser. The parser itself however has one requirement: `input:ParseInput`.

Is it possible to create a parser and later run it on arbitrary input?

**Comment by EECOLOR** [comment]
What I'm trying to achieve is implement the following:

```scala
object Parboiled2ParserAdapter extends Parser with ParserAdapter[Rule1] {

  var parserInput: Option[ParserInput] = None

  def input:ParserInput = parserInput.getOrElse(sys.error("No parser input available"))

  def predicate[X](f: String => X)(p: Char => Boolean):Rule1[X] =
    rule { capture(CharPredicate.from(p)) ~> f }

  def char[X](f: String => X)(char:Char):Rule1[X] =
    rule { capture(char) ~> f }

  def negative[X](f: String => X)(element:Rule1[_]):Rule1[X] =
    rule { capture( zeroOrMore( !element ~ ANY ) ) ~> f }

  def sequence[X, Y](f: ((X, X)) => Y)(head: Rule1[X], tail: Rule1[X]):Rule1[Y] =
    rule { (head ~ tail) ~> ((x1:X, x2:X) => f(x1 -> x2)) }

  def parse[X](adaptedGrammar: Rule1[X], value:String):X = {
    parserInput = Some(ParserInput(value))
    val result = __run(adaptedGrammar)
    parserInput = None
    result
  }
}
```

**Comment by sirthias** [comment]
Why can't you (re-)create a parser instance for every run?
Your solution will have terrible performance as it causes a reevaluatiion of `parserInput.getOrElse(...)` (which entails a function allocation) for **every** character?

**Comment by EECOLOR** [comment]
I know, I rather have the `parse` method just call `run` on the `adaptedGrammer`. 

How would you suggest creating a new parser? The `rule` macro needs to be called from within a `Parser`. The `predicate`, `char`, ..., functions are used to build parts of the total grammar.

With other parsers, rules are parsers themselves, that can be combined. Here the input and parse definition are tied together firmly. It would be great to have the different methods that return rules live without the input.

Is there any reason the input and the parser are tied together?

I don't mind creating a new parser for each input, but how can I create rules and feed them to the parser from the outside?

**Comment by sirthias** [comment]
Just implement your parser as a `class MyParser(val: input: ParserInput) extends Parser`.
Then, for every input, you create a new instance and run your top rule.
The examples show you how to do this.

**Comment by EECOLOR** [comment]
We might have some miscommunication.

I have code like the following:

```scala
// This code does not live inside a parser

def transform(definition): Rule1 = {
  // loop through definition and call the appropriate methods on the adapter
  definition loop {
    case x:X     => adapter.predicate(...)
    case y:Y     => adapter.negative(...)
    case z:Z     => adapter.char(...)
    case (a, b)  => adapter.sequence(transform(a), transform(b))
  }
}
val topRule = transform(externalDefinition)
```

How do I create an instance of a parser and feed it the top rule?

**Comment by sirthias** [comment]
If you want to build rules fully dynamically then pb2 might not be the right tool for the job.
Parboiled2 generates a parser **at compile-time**, not at run-time!
At run-time you are pretty much confined to setting the input and selecting a root-rule.

There is some very basic support for nested parsers (`runSubParser`) but it's not great yet.
We will change the pb2 basic design to allow for better composability at some point but currently parboiled2 is a pretty much a compile-time parser generator, similar to tools like ANTLR.

**Comment by EECOLOR** [comment]
Of course, fair point. I should have realized that myself.

Thank you for your time!
