### ISSUE TITLE
valueMap does not backtrack correctly

### ISSUE THREAD

**Issue by thesamet** [sirthias/parboiled2#136]
If the map contains two strings where one is a prefix of the other and valueMap tries the shorter one first, it will never backtrack and try the longer one. Example:

``` scala
import org.parboiled2._
import scala.util._

class TestParser(val input: ParserInput) extends Parser {
  val values = Map("12" -> 12, "123" -> 123)

  def InputLine = rule {
    valueMap(values) ~ EOI
  }
}

object Hello extends App {
  val parser = new TestParser("123")
  parser.InputLine.run() match {
    case Success(x) => println(x)
    case Failure(e: ParseError) => sys.error(parser.formatError(e, new ErrorFormatter(showTraces = true)))
    case x => println(x)
  }
}
```

The expectation is to parse "123" successfully, but this example fails with:

```
java.lang.RuntimeException: Invalid input '3', expected 'EOI' (line 1, column 3):
123
  ^
```

As a side note, since the order we try the pairs in the map matters (even if backtracking worked), it would be nice to have a version that takes Seq[(String, T)]

**Comment by sirthias** [comment]
Yes, this is clearly a bug.
Thanks for reporting!

**Comment by sirthias** [comment]
Just coming back to this: I don't think there is a clean fix that doesn't touch the API.
I'd recommend using a `ListMap` for now, but ultimately allowing for a `valueMap` as in the current design is simply a bad idea. We'll have to remove the feature and replace it with one that takes a `Seq[(String, T)]` as you already recommended.
