### ISSUE TITLE
Very small patterns

### ISSUE THREAD

**Issue by omidb** [sirthias/parboiled2#139]
Hi,
THANKS for awesome library, it made my life 10 times easier!
Is there any way (maybe syntactic sugar) to write a very simple "parser" without writing a whole class, like a method or something, let's say you want to have a parser to just parse `( x )` and return x.

**Comment by sirthias** [comment]
Thanks, Omid, for the feedback!

> Is there any way (maybe syntactic sugar) to write a very simple "parser" without writing a whole class, like a method or something, let's say you want to have a parser to just parse ( x ) and return x.

No, with parboiled 2.1 you have to extend `Parser` and create an instance before being able to parse. With parboiled 2.2 this won't be the case anymore.

PS: Please use the [Mailing List](https://groups.google.com/forum/#!forum/parboiled-user) for questions like this. We try to use the github tickets only for issue management. Thanks!
