### ISSUE TITLE
Redundancy in ABCParser example

### ISSUE THREAD

**Issue by Jasper-M** [sirthias/parboiled2#140]
In the `InputLine` rule of `ABCParser`, why is there the rule `!(ch('a') | 'b' | 'c')` at the end?
I am under the impression that the parser works just as well, and error reporting works even better, without it.

**Comment by alexander-myltsev** [comment]
Good question. I have no idea why it is required. 

@sirthias , would you shed some light on the history of that parser ?

**Comment by sirthias** [comment]
The question is whether we want to prevent the parser from recognizing input of the form `aabbccc`, i.e. with extra `c`s at the end. The negative syntactic predicate at the end somewhat shows off this parboiled feature. Of course you can leave it off.

Wikipedia also appears to have simplified the example to this:

```
S ← &A 'a'+ B
A ← 'a' A? 'b'
B ← 'b' B? 'c'
```

So, potentially we could do the same, but I don't think this is necessarily a priority.
