### ISSUE TITLE
Delivery scheme "throw" prints stack trace to console

### ISSUE THREAD

**Issue by pniederw** [sirthias/parboiled2#145]
parboiled2 should never print to the console but let the user handle the error. Also I'm not completely sure if the exception logic is as intended. I see a `ParseError` getting thrown, which is caught by `case NonFatal(e)` (which does `e.printStackTrace()`) rather than `case e: Fail`.

Both 2.1.0 (see class Parser) and HEAD (see class ParserState) have this problem.

**Comment by sirthias** [comment]
Yes, true on both accounts.
The `printStackTrace` needs to go and, if `scheme.parseError` throws, this shouldn't error shouldn't be caught by pb2 any more.
Thanks for the report!

**Comment by travisbrown** [comment]
Weirdly enough I just came here to report this very issue (in my case because of the noise in tests for a custom delivery scheme).

**Comment by sirthias** [comment]
Closed by 5261fab6b5441a8b395e20cececd58e482fa36c6.
