### ISSUE TITLE
Parsing cyrillic or chinese characters 

### ISSUE THREAD

**Issue by matthieu-ravey** [sirthias/parboiled2#147]
Hi,

I'm having trouble trying to parse cyrillic or chinese. I'm using ANY but it does seem to work with them. Is it possible ?

**Comment by sirthias** [comment]
pb2 doesn't support surrogate pairs, i.e. non-UTF16 characters that the JVM cannot represent in a single 16bit char value. If your characters are of that nature than, no, pb2 doesn't support them naturally.
You should be able to parse them "manually" though, i.e. by matching their individual sub-chars separately.
