### ISSUE TITLE
Infinite loop when capturing nonascii chars

### ISSUE THREAD

**Issue by Centaur** [sirthias/parboiled2#156]
```scala
import org.parboiled2._

class TestParser(val input: ParserInput) extends Parser {
    val nonascii = CharPredicate('\u0080' to '\uFFFF') // nonascii('中') == true

    def name: Rule1[String] = rule {
        capture (oneOrMore (nonascii) )
    }
}

object TestParser {
  def main(args: Array[String]) {
    new TestParser("中").name.run()
  }
}
```

This runs forever.

**Comment by JuPfu** [comment]
Hi Centaur,
the problem might be the collision between the definition of EOI in parboiled2 `val EOI = '\uFFFF'` and your definition of nonascii. Reducing the range of CharPredicate to ´\uFFFD` should return a result immediately.
Kind regards Jürgen

**Comment by Centaur** [comment]
Oh yes, this is exactly the problem.  @JuPfu Thank you very much for the help.
