### ISSUE TITLE
Make Code Citable

### ISSUE THREAD

**Issue by alexander-myltsev** [sirthias/parboiled2#158]
Hi Mathias, 

would you add this https://guides.github.com/activities/citable-code/ ?

**Comment by sirthias** [comment]
Alex,
the link appears to be broken.
What's this about?

**Comment by alexander-myltsev** [comment]
Mathias, 

I double checked it, and it is not broken. It is about DOI to make parboiled2 citable in a research paper:

> Digital Object Identifiers (DOI) are the backbone of the academic reference and metrics system. If you’re a researcher writing software, this guide will show you how to make the work you share on GitHub citable by archiving one of your GitHub repositories and assigning a DOI with the data archiving tool Zenodo.

Please, try again to open the link. If it does not work I'll find another way to show you the content.

**Comment by sirthias** [comment]
Ok, now I see.
I've never used or needed this citation support.
Do you need citability for your purposes?

Couldn't you make your fork citable?

**Comment by alexander-myltsev** [comment]
I think parboiled2 being citable might be useful for community. But no problems, I would make my fork citable.
