### ISSUE TITLE
publish 2.1.1_2.10

### ISSUE THREAD

**Issue by fommil** [sirthias/parboiled2#160]
you only published this release for scala 2.11, so we can't use it in our cross builds

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.parboiled%22%20AND%20a%3A%22parboiled_2.10%22

**Comment by bryce-anderson** [comment]
Has this issue been forgotten or is there not going to be artifacts for 2.10?

**Comment by fommil** [comment]
:cake:  :cherries:

**Comment by sirthias** [comment]
With Scala 2.11 now having been released almost 2 years ago and 2.10.5 out for a year
I was hoping to be able to simply drop the Scala 2.10 side of parboiled 2 since its maintenance isn't free.
How come you are still stuck on 2.10?

**Comment by fommil** [comment]
Ha! You must be kidding. Corporates are just upgrading to 2.10 now.

**Comment by sirthias** [comment]
Oh, man. So sad...
:)

I'll see whether I can get a 2.10 version of pb2 2.1.1 published today.

**Comment by fommil** [comment]
:smile: nice, then we can use 2.1.1 in our ENSIME crossbuild

**Comment by sirthias** [comment]
Ok, done.
2.1.1_2.10 has been published to sonatype and should appear on maven central soon.

**Comment by bryce-anderson** [comment]
Thanks! I'm not personally stuck on 2.10 but some users of the http4s
project are.

I agree that it's disappointing.
