### ISSUE TITLE
Backport fix for `.times` in Scala 2.12 from akka-http

### ISSUE THREAD

**Issue by jrudolph** [sirthias/parboiled2#162]
See #19815. It seems in 2.12 the expression to create a Range from an Int changed from

```
scala.this.Predef.intWrapper
```

to 

```
scala.Predef.intWrapper
```

which breaks `.times`.

**Comment by thjaeckle** [comment]
Any update on this backport?
@sirthias

**Comment by sirthias** [comment]
I don't really have the capacity to take a deeper look into this right now, but I'd be happy to merge a PR...

**Comment by sirthias** [comment]
I think this is actually fixed already.
