### ISSUE TITLE
shapeless 2.3.0

### ISSUE THREAD

**Issue by fommil** [sirthias/parboiled2#163]
new shapeless out, keep up at the back! :smile:

**Comment by fommil** [comment]
ok, looks like this is needed

**Comment by sirthias** [comment]
No problem, I'll publish a new pb2 release for 2.11 and 2.10 that's compiled against shapeless 2.3.0.
Since it's source compatible to 2.2.x it shouldn't really require any real work from my side.

**Comment by fommil** [comment]
Nice :smile: we should all get a little performance boost out of it

**Comment by fommil** [comment]
do you have automated publishing of snapshots to sonatype set up? Because that would be enough for us in the short term.

**Comment by sirthias** [comment]
Ok, done.
I've just published release 2.1.2 (for 2.11 and 2.10) to sonatype, which is built against shapeless 2.3.0.
Cheers!

**Comment by alexander-myltsev** [comment]
Mathias, are you missing the git-tag for 2.1.2?

**Comment by fommil** [comment]
oh, I thought you'd bump to 2.2.0 since this is binary breaking change. Not a big deal, but the semver gods will descend upon you.

**Comment by sirthias** [comment]
Yes, I thought about that, but internally I have already used 2.2 for other stuff.
So 2.1.2 its gonna be.
Bring on the semver gods, I'll deal with them! :)

**Comment by sirthias** [comment]
@alexander-myltsev Right. Just pushed.

**Comment by fommil** [comment]
2.3 ? :smile:
