### ISSUE TITLE
Publish 2.1.2 for Scala.JS

### ISSUE THREAD

**Issue by japgolly** [sirthias/parboiled2#165]
Hi I just noticed that you SJS support was added (nice! :+1:) prior to the release of 2.1.2.

Looking at the 2.1.2 release in Maven Central, it seems that only JVM artifacts were published:
http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.parboiled%22%20AND%20v%3A%222.1.2%22

**Comment by adrobisch** [comment]
Somebody already published a scalajs artifact in central from a `2.1.0`-fork  http://search.maven.org/#artifactdetails%7Ccom.github.japgolly.fork.parboiled%7Cparboiled_sjs0.6_2.11%7C2.1.0%7Cjar . Currently using that, would also be happy to see a (new) release for scalajs.

**Comment by japgolly** [comment]
That somebody is me :) I shouldn't need to maintain a fork anymore because this project now has official SJS support. It's there on master now and it was added before 2.1.2, it just wasn't published for some reason. /ping @sirthias @alexander-myltsev

**Comment by sirthias** [comment]
Scala.js support was merged with https://github.com/sirthias/parboiled2/pull/164, which came after the 2.1.2 release.

However, I have just published version 2.1.3 for both architectures (JVM and SJS), so if you upgrade to 2.1.3 you should be good.
(It might take a few hours for the artifacts to appear on Maven Central though...)

**Comment by adrobisch** [comment]
Thanks a lot!

**Comment by japgolly** [comment]
Oh thanks @sirthias. I just looked at the flat chronological commit history, I didn't realised the SJS commits came from the merge which was after 2.1.2. Thanks for publishing 2.1.3!

**Comment by sirthias** [comment]
No problem, @japgolly, have fun!
