### ISSUE TITLE
`andNot` seems to have a logical mistake

### ISSUE THREAD

**Issue by Primetalk** [sirthias/parboiled2#167]
`CharPredicate.andNot` is defined here:
https://github.com/sirthias/parboiled2/blob/release-2.1/parboiled-core/src/main/scala/org/parboiled2/CharPredicate.scala#L95-L96

It's name and one of the if-branches suggest that the result should be `this && ! that`. However, in case `this == Empty` it evaluates to only `!that` instead of `Empty`.

**Comment by sirthias** [comment]
Yes, you are perfectly right.
Would you like to submit a fix?
