### ISSUE TITLE
Linking cross-compiled project with ScalaJS and Scala 2.12.1

### ISSUE THREAD

**Issue by JuPfu** [sirthias/parboiled2#173]
I hope you had the chance to spend some relaxing hours with your family and friends during christmas holidays. 

Linking "fullOptJS" or "fastOptJS" with scala-js using Scala 2.12.1 does not find parboiled2 classes. 
The error messages emitted by sbt suggest that the problem is related to parboiled2. 
Do you have a clue, how to resolve the problem ?

Scala 2.11.8 is working fine. Cross-compiling for scala-js and linking "chelonaJS/fullOptJS" works fine.
In both cases the sbt build uses the sbt-scalajs plugin

    addSbtPlugin("org.scala-js" % "sbt-scalajs" % "0.6.14")

## Excerpt of build file for Scala 2.11.8:

    scalaVersion := "2.11.8"
    
    lazy val chelona = crossProject.in(file("."))
      .settings(libraryDependencies ++=
        Seq(
          "org.parboiled" %%% "parboiled" % "2.1.3",
          "com.chuusai" %%% "shapeless" % "2.3.0",
          "org.scalatest" %%% "scalatest" % "3.0.0" % Test)
        )
      .jvmSettings(
        libraryDependencies ++=
        Seq(
          "com.github.scopt" %% "scopt" % "3.5.0"
        )
      )
      .jsSettings( )

## Modifications of build file for Scala 2.12.1:

    scalaVersion := "2.12.1"
    
    lazy val chelona = crossProject.in(file("."))
      .settings(libraryDependencies ++=
        Seq(
          "org.parboiled" %%% "parboiled" % "2.1.3",
          "com.chuusai" %%% "shapeless" % "2.3.2",
          "org.scalatest" %%% "scalatest" % "3.0.1" % Test)
        )
      .jvmSettings(
        libraryDependencies ++=
        Seq(
          "com.github.scopt" %% "scopt" % "3.5.0"
        )
      )
      .jsSettings( )
 
Cross-compiling for scala-js gives no warnings or errors but linking "chelonaJS/fullOptJS" results in 

[info] Full optimizing /Users/jp/Downloads/chelona/js/target/scala-2.12/chelona-opt.js
[error] Referring to non-existent class org.parboiled2.support.Unpack$
[error]   called from org.chelona.TurtleParserJS$.parse(java.lang.String,scala.Boolean,scala.Boolean,java.lang.String,scala.Boolean)java.lang.String
[error]   called from org.chelona.TurtleParserJS$.$$js$exported$meth$parse(java.lang.String,scala.Boolean,scala.Boolean,java.lang.String,scala.Boolean)java.lang.Object
[error]   called from org.chelona.TurtleParserJS$.parse
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   org.chelona.TurtleParserJS$
[error] Referring to non-existent class org.parboiled2.Parser$DeliveryScheme$
[error]   called from org.chelona.TurtleParserJS$.parse(java.lang.String,scala.Boolean,scala.Boolean,java.lang.String,scala.Boolean)java.lang.String
[error]   called from org.chelona.TurtleParserJS$.$$js$exported$meth$parse(java.lang.String,scala.Boolean,scala.Boolean,java.lang.String,scala.Boolean)java.lang.Object
[error]   called from org.chelona.TurtleParserJS$.parse
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   org.chelona.TurtleParserJS$
[error] Referring to non-existent class org.parboiled2.ParseError
[error]   called from org.chelona.TurtleParserJS$.parse(java.lang.String,scala.Boolean,scala.Boolean,java.lang.String,scala.Boolean)java.lang.String
[error]   called from org.chelona.TurtleParserJS$.$$js$exported$meth$parse(java.lang.String,scala.Boolean,scala.Boolean,java.lang.String,scala.Boolean)java.lang.Object
[error]   called from org.chelona.TurtleParserJS$.parse
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   org.chelona.TurtleParserJS$
[error] Referring to non-existent method org.parboiled2.Parser$DeliveryScheme$.Try(org.parboiled2.support.Unpack$Aux)org.parboiled2.Parser$DeliveryScheme
[error]   called from org.chelona.TurtleParserJS$.parse(java.lang.String,scala.Boolean,scala.Boolean,java.lang.String,scala.Boolean)java.lang.String
[error]   called from org.chelona.TurtleParserJS$.$$js$exported$meth$parse(java.lang.String,scala.Boolean,scala.Boolean,java.lang.String,scala.Boolean)java.lang.Object
[error]   called from org.chelona.TurtleParserJS$.parse
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   org.chelona.TurtleParserJS$
[error] Referring to non-existent class org.parboiled2.Parser$
...

**Comment by sirthias** [comment]
Unfortunately I don't have enough experience with scalajs myself to quickly figure out the problem here.
The `"org.parboiled" %% "parboiled_sjs0.6" % "2.1.3"` artifact exists for Scala 2.12 (http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22parboiled_sjs0.6_2.12%22) and the JAR contains the `org.parboiled2.ParseError` class.
No idea why it's not found.

**Comment by JuPfu** [comment]
japgolly's [fix](https://github.com/sirthias/parboiled2/pull/174) Scala.js build for Scala 2.12 #174 solved the issue.
