### ISSUE TITLE
enable travis-ci

### ISSUE THREAD

**Issue by xuwei-k** [sirthias/parboiled2#175]

**Comment by xuwei-k** [comment]
https://travis-ci.org/sirthias/parboiled2/builds

🤔 

<img width="763" alt="screen shot 2018-09-14 at 20 28 42" src="https://user-images.githubusercontent.com/389787/45547747-cd8ef400-b85c-11e8-8d14-cd21f992dd41.png">

**Comment by sirthias** [comment]
Ok, now: https://travis-ci.org/sirthias/parboiled2

**Comment by xuwei-k** [comment]
👍 🎉
