### ISSUE TITLE
Referring to non-existent class error with ScalaJS

### ISSUE THREAD

**Issue by Vadi** [sirthias/parboiled2#180]
Using 

- ScalaJS Plugin 0.6.14
- Parboiled2 2.1.4
- Scala 2.12.2

Getting the error while running `fullOptJs` or `fastOptJs` -

`Referring to non-existent class org.parboiled2.support.Unpack$`

Looks like this issue was address in the past - #174
As a side note - The class I am JSExporting is taken from here - #161

Any help is greatly appreciated.

**Comment by Vadi** [comment]
Looks like this issue was address in the past - #174

**Comment by Vadi** [comment]
As a side note - The class I am JSExporting is taken from here - https://github.com/sirthias/parboiled2/pull/161

**Comment by sirthias** [comment]
Hi Vadi,
since I haven't used parboiled (or any other library) with ScalaJS myself yet I'm not really qualified to help with this issue.
If anyone else could chip in, that'd be much appreciated!

**Comment by JuPfu** [comment]
Hi Vadi, 
the [cheló̱na](https://github.com/JuPfu/chelona) project is based on Parboiled 2 and uses ScalaJS to convert RDF-data. Maybe, a glance at the build file gives you a hint. A next step might be downloading a copy of the project and generating a ScalaJS chelona_sjs0.6_2.12-1.3.0.jar by typing sbt chelonaJS/fullOptJS  . Opening the turtle.html file located in the js-tree with a browser should show a running example.
I hope these lines have been of some help.
![screenshot 2017-03-13 um 18 04 06](https://cloud.githubusercontent.com/assets/8527382/23866006/c28f023a-0817-11e7-960c-801215b597f6.png)

**Comment by Vadi** [comment]
Thanks for the help @JuPfu and @sirthias. The problem was my `build.sbt`. I missed to refer parboiled using`%%%`.  &ndash;

```
    libraryDependencies ++= Seq(
      "org.parboiled"                   %%%    "parboiled"                 %           "2.1.4",
      "com.chuusai"                    %%%    "shapeless"                 %           "2.3.2",
      "org.scalatest"                   %%%    "scalatest"                 %             "3.0.0"    %   "test"
    )
```
