### ISSUE TITLE
Case insensitive `valueMap`

### ISSUE THREAD

**Issue by alexander-myltsev** [sirthias/parboiled2#184]
There is a case https://gitter.im/sirthias/parboiled2?at=5a6b6ef46117191e61b80470

@sirthias , do you think it can be solved with the current armory of tools? Or do we need a PR?

**Comment by sirthias** [comment]
One hack could be to override `__matchMap` and `__matchMapWrapped`.
But this would of course change _all_ applications of `valueMap` at once.

If we want to support `valueMap` as well as a case-insensitive counterpart we'd need an addition to the library I'm afraid.
