### ISSUE TITLE
Scala 2.13 support

### ISSUE THREAD

**Issue by pshirshov** [sirthias/parboiled2#193]
Hi guys,

Do you have any plans on supporting 2.13 and Dotty?

**Comment by theon** [comment]
See https://github.com/sirthias/parboiled2/pull/194

**Comment by pshirshov** [comment]
Thanks!

**Comment by sirthias** [comment]
Just published release 2.1.5, which is also available for 2.13.0-M4.

**Comment by theon** [comment]
Thanks @sirthias!
