### ISSUE TITLE
Scala-native support

### ISSUE THREAD

**Issue by francisdb** [sirthias/parboiled2#198]
I was looking at using some parts of akka-http but it seems that the underlying akka-parse is embedding parboiled2 and shapeless. Shapeless is available for scala-native so only parboiled2 remains.

This would for now limit parboiled2 to scala 2.11 as scala-native 0.4.x with scala 2.12 support is not yet available. But that should be no problem as the current base platform is 2.10.

Looks like everything compiles without problems on scala native, only the specs2 dependency is an issue.

**Comment by francisdb** [comment]
@xuwei-k I see you already requested scala native upstream https://github.com/etorreborre/specs2/issues/591

**Comment by francisdb** [comment]
Any chance a native release could be pushed without the tests having run?

**Comment by sirthias** [comment]
To be honest, I have moved off specs2 and towards Scalatest or even @lihaoyi's utest on all my newer projects. So, if the specs2 dependency becomes a liability for a potential support of scala-native then I'd support a switch of test infrastructure to sth else.
That shouldn't be hard to do at all since, AFAIK, there is nothing specs2-specific that we really depend on in the tests...

**Comment by francisdb** [comment]
Indeed the fastest path here would be switching testing frameworks, so which test framework would you prefer?

**Comment by francisdb** [comment]
I see there is one test using ScalaCheck, that is [not yet released for scala native](https://github.com/rickynils/scalacheck/issues/396)

**Comment by sirthias** [comment]
I think we should move to https://github.com/lihaoyi/utest.
It does all we need and doesn't get in the way.
And the one test currently relying on ScalaCheck can surely be easily rewritten to a custom generator as well...

**Comment by lolgab** [comment]
I've published the artifact under my groupid having seen no interest about Scala Native by scalacheck maintainer. You can use `"com.github.lolgab" %%% "scalacheck" % "0.4.1"` as Scala Native dependency on other libraries.

**Comment by francisdb** [comment]
Let's see if I can get these tests ported to utest

looks like the utest-scalacheck example at https://github.com/lihaoyi/utest/issues/2 might allow to keep the scalacheck part (using @lolgab 's release)

**Comment by francisdb** [comment]
should I base on the `release-2.1` branch?

**Comment by sirthias** [comment]
@francisdb Yes, the `release-2.1` branch really should be the master...
The master is essentially a failed (due to capacity restriction on my side) attempt to pull the library to the next level.

**Comment by francisdb** [comment]
@sirthias the parboiled `-` macro seems to conflict with the parboiled `-` macro, any hints on how I can workaround that?

**Comment by sirthias** [comment]
Sorry, @francisdb, I don't understand you question...

**Comment by francisdb** [comment]
@sirthias I understand you don't understand, you will see what I mean once to PR is ready
