### ISSUE TITLE
fix DSLTest "diverging expansion" compile error with Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [sirthias/parboiled2#202]
- https://github.com/sirthias/parboiled2/commit/f12be8b65603cc66478c1b01591e975b561908c8
- https://github.com/sirthias/parboiled2/blob/63cf07d42b297dd2f9a3a0ff2833e096a957280f/build.sbt#L175-L189
- https://github.com/sirthias/parboiled2/pull/200

**Comment by sirthias** [comment]
Fixed in 2.1.6 release.
