### ISSUE TITLE
zeroOrMore and optional don't seem to work as documented.

### ISSUE THREAD

**Issue by fr-rustyphillips** [sirthias/parboiled2#204]
Using parboiled_2.12 v2.16
 
This:
```
 def TestZero: Rule1[Seq[String]] = rule (
    zeroOrMore(capture("aa"))
  )
```
and this:
```
 def TestZero: Rule1[Seq[String]] = rule (
    optional(oneOrMore(capture("aa")))
  )
```

Both produce this error:
```Expression of type Rule[HNil, StrictOut] doesn't conform to expected type Parboiled2.Rule1[Seq[String]]```

In contrast, this does work:
```
 def TestZero: Rule1[Seq[String]] = rule (
    oneOrMore(capture("aa"))
  )
```

According to the docs, this type should work.  Is there something different I should be doing for this to work?

**Comment by lebel-louisjacob** [comment]
I personally don't know why neither `optional[T](_: Rule1[T]): Rule1[Optional[T]]` nor `zeroOrMore[T](_: Rule1[T]): Rule1[Seq[T]]` are working.

On another hand, I think sharing a workaround --involving for sure some boilerplate-- may help:

```scala
def ZeroOrMore: Rule1[Seq[String]] = rule {
  oneOrMore(capture("str")) | push(Seq.empty)
}
```

**Comment by sirthias** [comment]
Your first snippet:

```scala
def TestZero: Rule1[Seq[String]] = rule (
    zeroOrMore(capture("aa"))
  )
```

should compile fine. (It does for me, using Scala 2.12.8)

Your second snippet produces this compile error:

```
[error] ...: type mismatch;
[error]  found   : org.parboiled2.Rule[shapeless.HNil,Option[scala.collection.immutable.Seq[String]] :: shapeless.HNil]
[error]  required: org.parboiled2.Rule[shapeless.HNil,Seq[String] :: shapeless.HNil]
[error]       optional(oneOrMore(capture("aa")))
```

which explains the problem quite well, because the `optional` produces an `Option`, which your method result type doesn't contain.

How do you manage to have the compiler produce the error you've quoted?

**Comment by fr-rustyphillips** [comment]
Upon looking deeper, it looks like this problem is actually only one with
the Scala plugins for Idea and Eclipse.
It seems to actually compile fine.

Considering that basically everything else has worked flawlessly for me, I
was under the impression that the tooling and the compiler were actually in
sync.
The workaround seems to work even when used with an IDE, so I'm probably
going to go with that just so that I can continue to use the IDE for
debugging purposes.

**Comment by sirthias** [comment]
Ok, thanks for digging up the source of the problem!
