### ISSUE TITLE
publish for Scala 2.13

### ISSUE THREAD

**Issue by xuwei-k** [sirthias/parboiled2#205]

**Comment by xuwei-k** [comment]
@sirthias 🙏

**Comment by sirthias** [comment]
Sorry for the delay here.
Just returned from 2 weeks of family vacation and will get this done today...

**Comment by sirthias** [comment]
Ok, just published release 2.1.7 to sonatype.
This release is cross-built across scala 2.11, 2.12 and 2.13 as well as scala-js for all these.
Should appear on maven central soon.

Thank you once again, @xuwei-k, for your support here!

**Comment by theon** [comment]
Awesome. Many thanks @sirthias!

**Comment by theon** [comment]
Awesome. Many thanks @sirthias!

**Comment by xuwei-k** [comment]
Thanks! 🎉 
https://repo1.maven.org/maven2/org/parboiled/parboiled_2.13/
