### ISSUE TITLE
Scala.js 1.0.0 support

### ISSUE THREAD

**Issue by theon** [sirthias/parboiled2#209]
Scala.js 1.0.0 has been released, can we publish a build?
https://www.scala-js.org/news/2020/02/25/announcing-scalajs-1.0.0/

Details for cross-building Scala.js 0.6.x and 1.x:
https://www.scala-js.org/news/2020/02/25/announcing-scalajs-1.0.0/#cross-building-for-scalajs-06x-and-1x

**Comment by sirthias** [comment]
Just published release 2.2.0 that is cross-built for scalajs 1.0 to sonatype.
Thanks to the continued updates applied by @xuwei-k the upgrade was actually quite easy.
Thank you, Kenji, for all your support!

**Comment by theon** [comment]
Thanks @xuwei-k, @sirthias!
