### ISSUE TITLE
StringIndexOutOfBoundsException in sliceString

### ISSUE THREAD

**Issue by magnus-madsen** [sirthias/parboiled2#213]
Hello!

We are happily using parboiled2 for the Flix parser.

On certain inputs, instead of seeing a normal parse error, we get:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: offset 55, count 2, length 56
	at java.base/java.lang.String.checkBoundsOffCount(String.java:3717)
	at java.base/java.lang.String.rangeCheck(String.java:298)
	at java.base/java.lang.String.<init>(String.java:294)
	at org.parboiled2.ParserInput$CharArrayBasedParserInput.sliceString(ParserInput.scala:118)
	at org.parboiled2.ErrorFormatter.formatProblem(ErrorFormatter.scala:80)
	at org.parboiled2.ErrorFormatter.format(ErrorFormatter.scala:58)
	at org.parboiled2.ErrorFormatter.format(ErrorFormatter.scala:51)
	at org.parboiled2.Parser.formatError(Parser.scala:106)
```

See https://github.com/flix/flix/issues/1352

I am happy to provide more information, if needed.

This is with parboiled-2.2.0 and Scala 2.13.

**Comment by sirthias** [comment]
Thank you, @magnus-madsen, for this report!
This is a bug, of course, that should be fixed.

Ideally we'd have a smallish, stand-alone example that reproduces the problem.
How hard do you think this would be in your case?
Does it happen in a complicated part of your grammar or in a fairly simple one?
Do you have any complicated parser actions that might be related or is this happen in a rule that is simply matching characters?

**Comment by magnus-madsen** [comment]
The grammar is quite long: https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala

We can easily reproduce the bug. For example, as shown in https://github.com/flix/flix/issues/1352 this program always triggers the crash:

```
def foo(): String = "bar"
def main(): String = foo()
d
```

I could try to fish out the relevant productions for you (but it will be difficult, if you want an executable program, not just to look at them). I don't think we have any complicated parser actions. I have a slight suspicion that this crash only happens when the parse error is at the end of the file (i.e. not somewhere in the middle). Does that help in any way?

For example, this does not crash, but prints a parse error as expected:

```
def foo(): String = "bar"
d
def main(): String = foo()
```

Just discovered that:

```
def foo(): String = "bar"
def main(): String = foo()
d

```

with a new line parses as well, so its seem likely that it is something with the end of the stream.

**Comment by sirthias** [comment]
Ok, thank you, that's helpful.
Can you point me to the place in your grammar where you define the `def` keyword that can only be partially matched in your example above?

**Comment by magnus-madsen** [comment]
Yes, it is here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L132

**Comment by magnus-madsen** [comment]
Maybe the problem is here:

https://github.com/flix/flix/blob/master/main/src/ca/uwaterloo/flix/language/phase/Parser.scala#L1441

where we try a negative match on an end of stream?

**Comment by sirthias** [comment]
Hmm... I couldn't really reproduce the source of the problem but there is a relatively easy fix that should avoid the exception you are seeing.

Just released parboiled 2.2.1 with the fix to sonatype. Should appear on Maven central soon.
Give it a spin!

**Comment by magnus-madsen** [comment]
Will do and report back.

**Comment by magnus-madsen** [comment]
The fix worked! Thank you very much :)

I just want to express my gratitude for your work on the parboiled2 library. 

It has been immensely useful for the Flix programming language. Without it I am not sure what our parsing story would have been and certainly we had to spend a lot more time on that aspect of the compiler. We have found the library to be very robust and fast.

**Comment by sirthias** [comment]
Thank you! That's great to hear!
I guess, now that the grammar is stable and everything, you might even be better served by moving to a hand-rolled parser, as most "real-world" compilers do, I think.
But initially, while still playing around with the grammar sth like pb2 can be a nice tool.
