### ISSUE TITLE
Scala Native (0.4+) support ?

### ISSUE THREAD

**Issue by oschrenk** [sirthias/parboiled2#226]
With Scala Native 0.4 now supporting Scala 2.12 and 2.13is it possible to add it back as a target?

**Comment by xuwei-k** [comment]
https://github.com/milessabin/shapeless/pull/1071

**Comment by oschrenk** [comment]
https://github.com/milessabin/shapeless/pull/1073
https://github.com/milessabin/shapeless/pull/1077

**Comment by xuwei-k** [comment]
Done in master branch https://github.com/sirthias/parboiled2/commit/f0859b43d305401c6e6df4848c75f5f789c8340e

@sirthias please release new version 🙏

**Comment by sirthias** [comment]
Just released version 2.3.0 with the recently merged scala-native support.
Thank you once again, @xuwei-k, for all your incredible work in maintaining this project!!
