### ISSUE TITLE
Website in the repository description is unrelated to the repository

### ISSUE THREAD

**Issue by koterpillar** [sirthias/parboiled2#266]
The repository's Website link is http://parboiled2.org/.

When I open that, there's no information about the library, it looks like this:

<img width="1203" alt="Agen Toto Play" src="https://user-images.githubusercontent.com/140276/125182961-d47d2180-e255-11eb-8dbe-e84a3fe8db2b.png">

Perhaps the domain lapsed and was purchased by an unrelated party?

**Comment by sirthias** [comment]
Yes, looking at this I am now somewhat sorry that I did let it slip in 2017.
AFAIR @alexander-myltsev registered it back then. I don't know what happened and why the domain now points so some weird gaming site. Maybe @alexander-myltsev can shed some light on this?

**Comment by alexander-myltsev** [comment]
Oh my... I missed the letter from the domains provider. And apparently, they sold it out. So sorry about that. Is there anything we can do to fix that now?

**Comment by sirthias** [comment]
It's unfortunate that we've lost the domain but it's not a real issue in the practical sense.
I've removed the pointer to http://parboiled2.org from the repo details, which should be enough to prevent people from tripping over this.

Thank you for reporting this, @koterpillar !

**Comment by koterpillar** [comment]
I'd like to point out that:

* The new owners can verify the domain on Sonatype or elsewhere and push a malicious update. (Unlikely given the current content, but the owners might sell it to highest bidder.)
* The development team can't repeat the verification if it's needed for any reason.

**Comment by sirthias** [comment]
Yes, this is indeed the most annoying consequence of the slipped domain and the reason that I will put more personal focus on all project domains in the future. Unfortunately I don't see a way to alleviate the situation regarding parboiled2.org.

**Comment by alexander-myltsev** [comment]
Alas, pretty annoying. I ordered "brokerage service" from the domain provider. They would make an attempt to buy the domain from the current holder. Let's hope for the best. I'll keep you updated.

**Comment by alexander-myltsev** [comment]
I got the reply from the domain provider. They say that the price might be thousands of dollars. I'd like to figure out if we could resolve the problem in steps as follows:

- remove all artifacts under `org.parboiled2` group from the Sonatype
- register a new domain, say, `parboiled2.io`
- publish all existing artifacts upon new domain (can find time to do it myself)

**Comment by sirthias** [comment]
We could do that but I don't think it's worth it, TBH.
There won't be many new users of parboiled2 anyway.
I'll keep an eye on the sonatype artifacts, in case someone published something fishy, but I think the risk is low...

**Comment by alexander-myltsev** [comment]
Hi all. Good news. I bought the domain parboiled2.org. There should be no surprises now.
