### ISSUE TITLE
Scala 3: very slow / hanging rule compilation for `~` chaining subrules

### ISSUE THREAD

**Issue by jrudolph** [sirthias/parboiled2#360]
As reported by @hughsimpson  in https://github.com/akka/akka-http/pull/4079#issuecomment-1091141651:

> found that if there were more than two non-literal subrules in a parser chained with ~ it basically takes forever to compile, unless you force right-associativity with parentheses (i.e. `ip-number` ~ ('.' ~ (`ip-number` ~ ('.' ~ `ip-number`))) compiles fast enough, but `ip-number` ~ '.' ~ `ip-number` ~ '.' ~ `ip-number` basically takes forever).

**Comment by jrudolph** [comment]
See https://github.com/akka/akka-http/pull/4097#issuecomment-1095002536:

> it looks I've found the core reason of the problem with TailSwitch https://github.com/lampepfl/dotty/issues/14903

**Comment by sirthias** [comment]
From looking at https://github.com/lampepfl/dotty/issues/14903 it looks like this problem can (or "is" or "will be") fixed on the Scala 3 compiler side and can be closed here...
