### ISSUE TITLE
Compilation broken against current dotty nightlies and likely for upcoming Scala 3.1.3

### ISSUE THREAD

**Issue by jrudolph** [sirthias/parboiled2#365]
Starting from 3.1.3-RC1-bin-20220404-ad2553d-NIGHTLY.

See https://github.com/lampepfl/dotty/issues/14903#issuecomment-1096885950 for information about would have to be changed to support Scala 3.1.3. Let's wait what will be the eventual result there.

Just changing `~` and `~!~` will not be enough, the macros need to be changed to match the new signature and probably the same needs to be done for the generated `ActionOps`.

**Comment by smarter** [comment]
I've opened https://github.com/lampepfl/dotty/pull/14987 which would fix the regression (as well as the performance issue) if accepted.

**Comment by jrudolph** [comment]
Thanks a lot @smarter :+1: 

The fix in https://github.com/lampepfl/dotty/pull/14987 works indeed, I checked with the latest 3.2.0-RC1 nightly snapshot.

I also added parboiled2 to the Scala 3 community build to be able to catch regressions earlier: https://github.com/lampepfl/dotty/pull/14911.
