### ISSUE TITLE
Question: Calling Parboiled 2 from Kotlin

### ISSUE THREAD

**Issue by binkley** [sirthias/parboiled2#409]
I have Kotlin project using Parboiled 1, and I'd like to investigate migrating to Parboiled 2.
Are there any resources this project or others have shared?

Ref: https://github.com/binkley/kotlin-dice/issues/133

**Comment by sirthias** [comment]
Hey @binkley, I don't think it's possible to use parboiled2 from any other language than Scala.
While the first version generated the actual low-level parser code at runtime parboiled 2 switched to macro-based parser generation that is done by the Scala compiler at compile time.
While this has a number of benefits over the earlier approach it also means that, without the Scala compiler, parboiled 2 is entirely useless.
In fact, pb2 is very much Scala-only...
