### ISSUE TITLE
Update scalafmt to latest version

### ISSUE THREAD

**Issue by mdedetrich** [sirthias/parboiled2#425]
The scalafmt in this project is using a pretty old version so we should look into updating it (the newest version of scalafmt has a lot of new features, especially wrt new dialects like Scala3). The problematic bit is that the new version of scalafmt has a lot of changes in the config and so it may take quite a bit of work to to make sure there isn't a diff resulting from the upgrade (and realistically speaking it may be impossible to have no diff when updating).

Regardless after https://github.com/sirthias/parboiled2/issues/424 is resolved it can be said that now is an opportune time to update scalafmt even if it does cause a diff because there is only one major PR open at https://github.com/sirthias/parboiled2/pull/53 which is quite outdated anyways so it will cause minimum friction to the project.

I can look into this, the only question is whether I should spend a lot of effort in minimizing the diff from a scalafmt upgrade by tinkering around with the various `.scalafmt.conf` settings or whether we should just accept the changes that the new version of scalafmt will bring in. Note that in the case of having a diff, you can use `.git-blame-ignore-revs` (see https://github.com/apache/incubator-pekko-http/blob/main/CONTRIBUTING.md#ignoring-formatting-commits-in-git-blame) which will make `git blame` ignore the scalafmt diff (since its useful/relevant).

@sirthias @xuwei-k

**Comment by sirthias** [comment]
I agree that we should update scalafmt and it's absolutely not requirement for me to minimize the diff.
If there are not open PRs then there shouldn't be any issues, because this project doesn't have any work ongoing AFAIK.

**Comment by mdedetrich** [comment]
Perfect, I will look into this once I solve the existing problems.

**Comment by sirthias** [comment]
👍 
Thank you so much for all your work here, Matthew!

**Comment by sirthias** [comment]
Ok, enabled branch protection with `Code is formatted` and `test (17)` checks.
