### ISSUE TITLE
Make a new release when Scala 3.3 LTS comes out?

### ISSUE THREAD

**Issue by mdedetrich** [sirthias/parboiled2#428]
I need to double check how this works exactly but basically Scala 3 changed the strategy when it comes to backwards/forwards breaking. Due to this Scala 3 now has a concept of LTS, which an upcoming Scala 3.3 version will be one of those LTS releases.

Since technically speaking a backwards breaking change was merged into `master` (see https://github.com/sirthias/parboiled2/pull/417#issuecomment-1455714329), there is merit in making a new release of parboiled2 that has both this breaking change along with others (like Scala 3.3).

**Comment by mdedetrich** [comment]
Question posed in Scala discord https://discord.com/channels/632150470000902164/632150470000902166/1082226125599690753

**Comment by sirthias** [comment]
Completed with 2.5.0.
