### ISSUE TITLE
get Parboiled2 to compile with Scala-JS

### ISSUE THREAD

**Issue by bblfish** [sirthias/parboiled2#77]
http://www.scala-js.org/ is moving along very quickly. Having a good parser on the client would be very neat. As Parboiled2 is pure Scala, it should be possible to get it to work for Scala-JS. :-)

**Comment by alexander-myltsev** [comment]
This can be closed.

**Comment by danielwegener** [comment]
Uhm - can it? Imo it would be great to have a _proper_ release in central and future versions of parboiled 2 in as scalajs artifact too.

**Comment by danielwegener** [comment]
Uhm. Just curious. Will it be ported back to this repo and released in central? :)

**Comment by sirthias** [comment]
Daniel, I currently don't have time to pick this up, but the next pb2 version will be scala-js compatible by itself...

**Comment by danielwegener** [comment]
Hi Matthias :) No rush, I just was worried about the "can be closed" comment - I just read it as "nvm, solved in a fork".

**Comment by matthieu-ravey** [comment]
@sirthias that'd be really cool ! Do you have any idea when the next version of pb2 will be released ?

**Comment by vhiairrassary** [comment]
@matthieu-ravey pb2 should be released soon: https://github.com/sirthias/parboiled2/commit/25f937bb87496cd0cc1e89dac5f75612b5ca4795

**Comment by vhiairrassary** [comment]
@sirthias Hello, we are working on adding support scala.js to pb2 but as scala.js does not support java sources the file [Base64.java](https://github.com/sirthias/parboiled2/blob/release-2.1/parboiled-core/src/main/java/org/parboiled2/util/Base64.java) cannot be compiled.

Will you be ok to merge a pull request that rewrite it in scala + add support to scala.js in build.sbt ? (Just commenting [Base64Parsing.scala](https://github.com/sirthias/parboiled2/blob/release-2.1/parboiled/src/main/scala/org/parboiled2/Base64Parsing.scala) which is the alone class to use Base64.java allow us to use pb2 in js and it rocks !)

**Comment by sirthias** [comment]
Victor, yes, having a proper port of Base64.java to Scala would be great.
Maybe it could even be done almost automatically, IntelliJ appears to have an automatic converter that could maybe provide at least a good basis for the port.

**Comment by vhiairrassary** [comment]
@sirthias https://github.com/sirthias/parboiled2/pull/161
